### ISSUE TITLE
Make it responsive

### ISSUE THREAD

**Issue by Arun0021** [Arun0021/Snake-Game#1]
you can make it responsive 
plus add button for the movement and 
dont delete anything just comment it down
#goodfirstissue
#firstcommit
make it playable on mobile by making it responsive
plus add buttons for the movement

**Comment by Arun0021** [comment]
Hi Best of Luck

**Comment by Bashamega** [comment]
Assign me please.

**Comment by Arun0021** [comment]
ok, so
first of all you can add buttons in it using javascript so that we can play is using buttons instead of touchpad
and after that you can make it responsive so that we can play the game in mobile as well 
apart from that if background doesnot suits you can change it according to the responsive window i mean new bg for small screen 
alright 
best of luck

**Comment by Bashamega** [comment]
> ok, so first of all you can add buttons in it using javascript so that we can play is using buttons instead of touchpad and after that you can make it responsive so that we can play the game in mobile as well apart from that if background doesnot suits you can change it according to the responsive window i mean new bg for small screen alright best of luck

Ok, It will be done by this week, please assign me to the issue
